# ======================
# I/O
# ======================
output_path: /app/runs/runs/results
output_name: test_zonal

write_dataframe: False
output_type: argmax  # [argmax / class_prob]
cog_conversion: False

# ======================
# Model & Inference
# ======================
model_weights: /app/runs/flair/FLAIR-HUB_LC-A_RGB_swinbase-upernet.safetensors
use_gpu: True
batch_size: 8
num_worker: 4 # 0 on Windows OS

img_pixels_detection: 512
margin: 40
output_px_meters: 0.2

# ======================
# Model Framework
# ======================
monotemp_arch: swin_base_patch4_window12_384-upernet
multitemp_model_ref_date: 05-15

# ======================
# Modalities (inputs used for inference)
# ======================
modalities:

  inputs:
      AERIAL_RGBI       : True
      AERIAL-RLT_PAN    : False
      DEM_ELEV          : False
      SPOT_RGBI         : False
      SENTINEL2_TS      : False 
      SENTINEL1-ASC_TS  : False
      SENTINEL1-DESC_TS : False

  AERIAL_RGBI:
      input_img_path: /app/data/aigle_aerial_yolov_2022_martinique_97225_v1.1/sources-raw/972-2022-0690-1630-U20N-0M20-E080.jp2
      channels: [1, 2, 3]
      normalization:
        type: custom
        means: [105.66, 111.35, 102.18]
        stds: [52.23, 45.62, 44.30]

  AERIAL-RLT_PAN:
      input_img_path: /path/to/input_image.tif
      channels: [1]
      normalization:
        type: custom
        means: [125.92]
        stds: [38.45]

  DEM_ELEV:
      input_img_path: /path/to/input_image.tif
      channels: [4, 1, 2]
      normalization:
        type: custom
        means: [1137.03, 433.26, 467.77]
        stds: [543.11, 312.76, 284.61] 
      calc_elevation : True
      calc_elevation_stack_dsm : True 

  SPOT_RGBI:
      input_img_path: /path/to/input_image.tif 
      channels: [4, 1, 2]
      normalization:
        type: custom
        means: [1137.03, 433.26, 467.77]
        stds: [543.11, 312.76, 284.61]

  SENTINEL2_TS:
      input_img_path: /path/to/input_image.tif
      channels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      dates_txt: /datesSEN2.txt
      filter_clouds: True
      filter_clouds_img_path: /path/to/input_image_MSK-SC.tif
      temporal_average: False

  SENTINEL1-ASC_TS:
      input_img_path: /path/to/input_image.tif
      channels: [1, 2]
      dates_txt: 
      temporal_average: False

  SENTINEL1-DESC_TS :
      input_img_path: /path/to/input_image.tif
      channels: [1, 2]
      dates_txt: 
      temporal_average: False

# ======================
# Tasks
# ======================
tasks:

  - name: AERIAL_LABEL-COSIA
    active: True
    class_names:
      0: building
      1: greenhouse
      2: swimming_pool
      3: impervious surface
      4: pervious surface
      5: bare soil
      6: water
      7: snow
      8: herbaceous vegetation
      9: agricultural land
      10: plowed land
      11: vineyard
      12: deciduous
      13: coniferous
      14: brushwood
      15: clear cut
      16: ligneous
      17: mixed
      18: undefined

  - name: ALL_LABEL-LPIS
    active: False
    class_names:
      0: grasses
      1: wheat
      2: barley
      3: maize
      4: other cereals
      5: rice
      6: flax/hemp/tobacco
      7: sunflower
      8: rapeseed
      9: other oilseed crops
      10: soy
      11: other protein crops
      12: fodder legumes
      13: beetroots
      14: potatoes
      15: other arable crops
      16: vineyard
      17: olive groves
      18: fruits orchards
      19: nut orchards
      20: other permanent crops
      21: mixed crops
      22: background

