# SLURM

paths :   

    out_folder: /app/data/flair-results/
    out_model_name: aigle-flair-seg

    train_csv: /app/flair-for-aigle/csv/FLAIR-HUB_TOY-DATASET_TRAIN.csv
    val_csv: /app/flair-for-aigle/csv/FLAIR-HUB_TOY-DATASET_VALID.csv
    test_csv: /app/flair-for-aigle/csv/FLAIR-HUB_TOY-DATASET_TEST.csv
    global_mtd_folder: /app/data/datasets/external/FLAIR-HUB_TOY
    ckpt_model_path: /app/runs/flair/FLAIR-HUB_LC-A_RGB_swinbase-upernet.safetensors


tasks: 

    train: True
    train_tasks: 
        init_weights_only_from_ckpt: True
        resume_training_from_ckpt: True

    predict: True
    write_files: True
    georeferencing_output: True

    metrics_only: False

hyperparams:

    num_epochs: 150
    batch_size: 2
    seed: 2025
    learning_rate: 0.00005

    optimizer: adamw  # [sgd / adam / adamw]
    optim_weight_decay: 0.01
    optim_betas: [0.9, 0.999]

    scheduler: one_cycle_lr #  [one_cycle_lr / reduce_on_plateau / cycle_then_plateau]
    warmup_fraction: 0.2 # if using one_cycle_lr. [0-1]
    plateau_patience: 10 # if using cycle_then_plateau

hardware:
    accelerator: 'gpu'
    num_nodes: 1
    gpus_per_node: 1
    strategy: 'auto' # ddp_find_unused_parameters_true if num_nodes > 1
    num_workers: 0

saving:   
    ckpt_save_also_last: True
    ckpt_weights_only: False
    ckpt_monitor: 'val_miou'
    ckpt_monitor_mode: 'max'
    ckpt_earlystopping_patience: 20
    cp_csv_and_conf_to_output: True
    enable_progress_bar: True
    progress_rate: 10
    ckpt_verbose: True
    verbose_config: True
